############################ Default configuration ############################
# rather than just use http://localhost:1313/
# add 127.0.0.1 local.shadowcryptic.com to /private/etc/hosts
baseURL: http://local.shadowcryptic.com:1313/
defaultContentLanguage: en
theme: CodeIT
# themesDir: ../..
title: ShadowCryptic
enableRobotsTXT: true
enableGitInfo: false
enableEmoji: true
ignoreErrors:
  - error-remote-getjson
  - error-missing-instagram-accesstoken
languages:
  en:
    weight: 1
    languageCode: en
    languageName: English
    hasCJKLanguage: false
    paginate: 12
    googleAnalytics: ''
    copyright: >-
      This work is licensed under a Creative Commons Attribution-NonCommercial
      4.0 International License.
    menu:
      main:
        - identifier: posts
          pre: ''
          post: ''
          name: Posts
          url: /posts/
          title: ''
          weight: 1
        - identifier: tags
          pre: ''
          post: ''
          name: Tags
          url: /tags/
          title: ''
          weight: 2
        - identifier: categories
          pre: ''
          post: ''
          name: Categories
          url: /categories/
          title: ''
          weight: 3
        - identifier: documentation
          pre: ''
          post: ''
          name: Docs
          url: /categories/documentation/
          title: ''
          weight: 4
        - identifier: about
          pre: ''
          post: ''
          name: About
          url: /about/
          title: ''
          weight: 5
        - identifier: github
          pre: <i class='fab fa-github fa-fw'></i>
          post: ''
          name: ''
          url: 'https://github.com/timecode/CloudflarePagesPoC'
          title: GitHub
          weight: 6
    params:
      description: ShadowCryptic stuff!
      keywords:
        - Theme
        - Hugo
      app:
        title: ShadowCryptic
        noFavicon: false
        svgFavicon: ''
        themeColor: '#ffffff'
        iconColor: '#5bbad5'
        tileColor: '#da532c'
      search:
        enable: false
        type: algolia
        contentLength: 4000
        placeholder: ''
        maxResultLength: 10
        snippetLength: 30
        highlightTag: em
        absoluteURL: false
      home:
        rss: 10
        profile:
          enable: true
          gravatarEmail: ''
          avatarURL: /images/ShadowCryptic-LogoAndTextPadded-800x800.png
          avatarAlt: ''
          title: ''
          subtitle: A blog of how-to's and associated cryptic code
          typeit: true
          social: false
          disclaimer: ''
        posts:
          enable: true
          paginate: 6
      social:
        GitHub: xxxx
        Linkedin: ''
        Twitter: xxxx
        Instagram: xxxx
        Facebook: xxxx
        Telegram: xxxx
        Medium: ''
        Gitlab: ''
        Youtubelegacy: xxxx
        Youtubecustom: ''
        Youtubechannel: ''
        Tumblr: ''
        Quora: ''
        Keybase: ''
        Pinterest: ''
        Reddit: ''
        Codepen: ''
        FreeCodeCamp: ''
        Bitbucket: ''
        Stackoverflow: ''
        Weibo: ''
        Odnoklassniki: ''
        VK: ''
        Flickr: ''
        Xing: ''
        Snapchat: ''
        Soundcloud: ''
        Spotify: ''
        Bandcamp: ''
        Paypal: ''
        Fivehundredpx: ''
        Mix: ''
        Goodreads: ''
        Lastfm: ''
        Foursquare: ''
        Hackernews: ''
        Kickstarter: ''
        Patreon: ''
        Steam: ''
        Twitch: ''
        Strava: ''
        Skype: ''
        Whatsapp: ''
        Zhihu: ''
        Douban: ''
        Angellist: ''
        Slidershare: ''
        Jsfiddle: ''
        Deviantart: ''
        Behance: ''
        Dribbble: ''
        Wordpress: ''
        Vine: ''
        Googlescholar: ''
        Researchgate: ''
        Thingiverse: ''
        Devto: ''
        Gitea: ''
        XMPP: ''
        Matrix: ''
        Bilibili: ''
        Email: xxxx@xxxx.com
        RSS: true
        Orcid: ''
        Mastodon:
          id: '@xxxx'
          prefix: 'https://mastodon.technology/'
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
author:
  name: ShadowCryptic
  email: ''
  link: ''
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
Permalinks:
  posts: ':filename'
privacy:
  googleAnalytics: {}
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
mediaTypes:
  text/plain:
    suffixes:
      - md
outputFormats:
  MarkDown:
    mediaType: text/plain
    isPlainText: true
    isHTML: false
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - MarkDown
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML
